import Navbar from "./Navbar/Navbar.jsx"
import Hero from "./Hero/Hero.jsx"
import About from "./About/About.jsx"
import Button from "./Button/Button.jsx"
import Services from "./Services/Services.jsx"
import Feedback from "./Feedback/Feedback.jsx"
import Footer from "./Footer/Footer.jsx"
import Pricing from "./Pricing/Pricing.jsx"
import CheckIn from "./CheckIn/CheckIn.jsx"
import Plan from "./Plan/Plan.jsx"
export { Navbar, Hero, About, Button, Services, Feedback, Pricing, CheckIn, Footer, Plan }